### ISSUE TITLE
[pail] List of Features and TODOs

### ISSUE THREAD

**Issue by prisis** [visulima/visulima#333]
# Missing Features
- [x] console table
- [x] add reduct https://github.com/visulima/visulima/pull/423
- [ ] added object tree
- [x] add progress
- [x] allow error after a string https://github.com/visulima/visulima/pull/389
 ```js
pail.error("Operation failed", new Error("Unable to acquire lock"));
```
- [x] add a simple reporter https://github.com/visulima/visulima/pull/418

# Fix
- [x] fix the interactive-manager output, check the  node interactive-manager.js output, is missing the messages

# TODOs
- [ ] add more docs
- [x] check why the logger strips spaces
```js
// should have a line break and 4 spaces
pail.info("\n    test ");
```
