### ISSUE TITLE
[fs] List of Features and TODOs

### ISSUE THREAD

**Issue by prisis** [visulima/visulima#338]
# Missing Features
- [x] readFile and readFileSync https://github.com/visulima/visulima/pull/340
- [x] readJson and readJsonSync https://github.com/visulima/visulima/pull/341
- [x] isAccessibleSync and isAccessible https://github.com/visulima/visulima/pull/339
- [x] writeFile and writeFileSync https://github.com/visulima/visulima/pull/341
- [x] writeJson and writeJsonSync https://github.com/visulima/visulima/pull/341
- [x] emptyDir, emptyDirSync https://github.com/visulima/visulima/pull/348
- [x] readYaml, readYamlSync, writeYaml and writeYamlSync https://github.com/visulima/visulima/pull/351
~readyCsv, readCsvSync, readCsvStream, writeCsv, writeCsvStream and writeCsvSync~ use https://github.com/C2FO/fast-csv or some other csv package
- [x] remove, removeSync https://github.com/visulima/visulima/pull/354
- [x] ensureSymlink and ensureSymlinkSync https://github.com/visulima/visulima/pull/350
- [x] ensureLink, ensureLinkSync, ensureDir, ensureDirSync, ensureFile and ensureFileSync https://github.com/visulima/visulima/pull/355
- [ ] allow findUp and findUpSync to follow symlinks
- [x] use https://github.com/unjs/pathe for collect and find-up [BREAKING CHANGE] https://github.com/visulima/visulima/pull/365

# TODOs
- [ ] Try to find a way to use symlinks to 100% on windows

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/visulima) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/visulima/visulima/issues/338">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/visulima/visulima/issues/338/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/visulima/visulima/issues/338/pledge.svg">
</picture>
</a>
